[project]
name = "radagent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Radman", email = "radikahn@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "botocore[crt]>=1.43.107",
    "python-dotenv>=1.2.4",
    "strands-harness>=0.1.2",
]

[project.scripts]
radagent = "radagent.main:main"

[build-system]
requires = ["uv_build>=0.12.19,<0.13.0"]
build-backend = "uv_build"
